# Generated by Django 6.0.7 on 2026-08-04 22:21

import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('total_capacity', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('rows'), '*', models.F('columns')), output_field=models.PositiveIntegerField())),
            ],
        ),
    ]
