# Generated by Django 6.0.7 on 2026-08-04 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('THRILLER', 'Thriller'), ('SCI_FI', 'Science Fiction'), ('ANIMATION', 'Animation')], max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
